version: '2'
services:
  etcd:
    image: quay.io/coreos/etcd
    ports:
    - 2379:2379
    - 2380:2380
    volumes:
    - etcd_data:/etcd_data
    command:
    - /usr/local/bin/etcd
    - -name
    - etcd0
    - --data-dir
    - /etcd_data
    - -advertise-client-urls
    - http://etcd:2379
    - -listen-client-urls
    - http://0.0.0.0:2379
    - -initial-advertise-peer-urls
    - http://etcd:2380
    - -listen-peer-urls
    - http://0.0.0.0:2380
  service:
    build: .
    volumes:
    - .:/code
    command:
    - gunicorn
    - server:__hug_wsgi__
    - -k
    - gevent
    - --bind
    - 0.0.0.0:8000
    - --reload
  envoy:
    image: envoyproxy/envoy:latest
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
    - "8000:80"

volumes:
  etcd_data: